<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LibTargetFrameworks)</TargetFrameworks>
    <AssemblyName>Opc.Ua.Sample</AssemblyName>
    <PackageId>Opc.Ua.Sample</PackageId>
    <RootNamespace>Opc.Ua.Sample</RootNamespace>
    <Description>OPC UA Sample Class Library</Description>
    <NoWarn>$(NoWarn);CA1852</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <ModelSourceGeneratorUseAllowSubtypes>true</ModelSourceGeneratorUseAllowSubtypes>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="TestData\TestDataDesign.xml" />
    <AdditionalFiles Include="TestData\TestDataDesign.csv" />
    <AdditionalFiles Include="MemoryBuffer\MemoryBufferDesign.xml" />
    <AdditionalFiles Include="MemoryBuffer\MemoryBufferDesign.csv" />
    <AdditionalFiles Include="Boiler\BoilerDesign.xml" />
    <AdditionalFiles Include="Boiler\BoilerDesign.csv" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net462'">
    <Reference Include="System.IdentityModel" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.11" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Configuration" Version="2.0.0-preview.3" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Core" Version="2.0.0-preview.3" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Server" Version="2.0.0-preview.3" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.SourceGeneration" Version="2.0.0-preview.3" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
