<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>AggregationClient</RootNamespace>
    <AssemblyName>AggregationClient</AssemblyName>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\..\..\bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\..\..\bin\Release\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="App.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Quickstarts.AggregationClient.Config.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Samples\ClientControls.Net4\UA Client Controls.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console">
      <Version>10.0.8</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client">
      <Version>1.5.378.156</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="WriteValueDlg.Designer.cs" />
    <Compile Remove="WriteValueDlg.cs" />
    <Compile Remove="TutorialModel.DataTypes.cs" />
    <Compile Remove="TutorialModel.Constants.cs" />
    <Compile Remove="SubscribeDataDlg.Designer.cs" />
    <Compile Remove="SubscribeDataDlg.cs" />
    <Compile Remove="CallMethodDlg.Designer.cs" />
    <Compile Remove="CallMethodDlg.cs" />
    <Compile Remove="AggregationModel.DataTypes.cs" />
    <Compile Remove="AggregationModel.Constants.cs" />
  </ItemGroup>
  <ItemGroup Label="EmbeddedResource items now included by globbing that were not in the original project file">
    <EmbeddedResource Remove="WriteValueDlg.resx" />
    <EmbeddedResource Remove="SubscribeDataDlg.resx" />
    <EmbeddedResource Remove="CallMethodDlg.resx" />
  </ItemGroup>
</Project>