<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Quickstarts.DataTypes</RootNamespace>
    <AssemblyName>Quickstarts.DataTypesServer</AssemblyName>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <SignManifests>false</SignManifests>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="App.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="DataTypesServer.Config.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </Content>
    <Content Include="Instances\ModelDesign2.xml" />
    <Content Include="Instances\Quickstarts.DataTypes.Instances.NodeSet.xml" />
    <Content Include="Instances\Quickstarts.DataTypes.Instances.PredefinedNodes.xml" />
    <Content Include="BuildDesign.bat" />
    <Content Include="Instances\ModelDesign2.csv" />
    <EmbeddedResource Include="Instances\Quickstarts.DataTypes.Instances.PredefinedNodes.uanodes" />
    <Content Include="Instances\Quickstarts.DataTypes.Instances.Types.bsd" />
    <Content Include="Instances\Quickstarts.DataTypes.Instances.Types.xsd" />
    <None Include="..\README.md">
      <Link>README.md</Link>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Samples\ServerControls.Net4\UA Server Controls.csproj" />
    <ProjectReference Include="..\Common\DataTypes Library.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console">
      <Version>10.0.8</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Server">
      <Version>1.5.378.156</Version>
    </PackageReference>
  </ItemGroup>
</Project>