<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Opc.Ua.Sample</RootNamespace>
    <AssemblyName>Opc.Ua.SampleClient</AssemblyName>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <StartupObject>Opc.Ua.Sample.Program</StartupObject>
    <AssemblyOriginatorKeyFile></AssemblyOriginatorKeyFile>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="App.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Opc.Ua.SampleClient.Config.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </Content>
    <Content Include="Opc.Ua.SampleClient.Endpoints.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClientControls.Net4\UA Client Controls.csproj" />
    <ProjectReference Include="..\Hosting\Opc.Ua.Samples.Hosting.csproj" />
    <ProjectReference Include="..\Controls.Net4\UA Sample Controls.csproj" />
    <ProjectReference Include="..\Opc.Ua.Sample\Opc.Ua.Sample.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="app.manifest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions">
      <Version>10.0.11</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Bindings.Https">
      <Version>2.0.0-preview.3</Version>
    </PackageReference>
    </ItemGroup>
  <PropertyGroup />
</Project>