<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Quickstarts.Views.Server</RootNamespace>
    <AssemblyName>Quickstarts.ViewsServer</AssemblyName>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\..\..\bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\..\..\bin\Release\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="App.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <AdditionalFiles Include="Model\ModelDesign.xml" />
    <AdditionalFiles Include="Model\ModelDesign.csv" />
    <AdditionalFiles Include="Model\Engineering\EngineeringDesign.xml" />
    <AdditionalFiles Include="Model\Engineering\EngineeringDesign.csv" />
    <AdditionalFiles Include="Model\Operations\OperationsDesign.xml" />
    <AdditionalFiles Include="Model\Operations\OperationsDesign.csv" />
    <Content Include="Quickstarts.ViewsServer.Config.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Samples\ServerControls.Net4\UA Server Controls.csproj" />
    <ProjectReference Include="..\..\..\Samples\Hosting\Opc.Ua.Samples.Hosting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Server">
      <Version>$(OpcUaNetStandardVersion)</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.SourceGeneration" Version="$(OpcUaNetStandardVersion)" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>