<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Opc.Ua.Gds.Client.Controls</RootNamespace>
    <AssemblyName>Opc.Ua.Gds.Client.Controls</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Controls\DiscoveryControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\EditValueCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\ImageListControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\ServerStatusControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\TrustListControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console">
      <Version>10.0.10</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client">
      <Version>2.0.0-preview.2</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Gds.Client.Common">
      <Version>2.0.0-preview.2</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ClientControls.Net4\UA Client Controls.csproj" />
  </ItemGroup>
</Project>
