version: '3.3'
services:
    gds:
      image: 'gds:latest'
      build: .
      restart: always
      network_mode: host
      # As an alternative to network_mode host you can specify a hostname and expose the ports as defined below
      #ports:
      #    - '58810:58812'
      #hostname: <hostname>
      #environment:
      #    - '58810'
      volumes:
          # exposing the whole .local/share directory, since the location of your application data depends on the name you set in the config file
          - './GDS-data/data:/root/.local/share/'
          # exposing the binary directory, since the the GDS Config file (Opc.Ua.GlobalDiscoveryServer.Config.xml) also lies there
          - './GDS-data/config/:/gds/config'