//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opc.Ua.Gds.Server.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.ApplicationNames = new HashSet<ApplicationName>();
            this.ServerEndpoints = new HashSet<ServerEndpoint>();
            this.CertificateRequests = new HashSet<CertificateRequest>();
            this.CertificateStores = new HashSet<CertificateStore>();
        }
    
        public int ID { get; set; }
        public System.Guid ApplicationId { get; set; }
        public string ApplicationUri { get; set; }
        public string ApplicationName { get; set; }
        public int ApplicationType { get; set; }
        public string ProductUri { get; set; }
        public string ServerCapabilities { get; set; }
        public byte[] Certificate { get; set; }
        public byte[] HttpsCertificate { get; set; }
    
        public virtual ICollection<ApplicationName> ApplicationNames { get; set; }
        public virtual ICollection<ServerEndpoint> ServerEndpoints { get; set; }
        public virtual ICollection<CertificateRequest> CertificateRequests { get; set; }
        public virtual ICollection<CertificateStore> CertificateStores { get; set; }
    }
}
