//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opc.Ua.Gds.Server.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationName
    {
        public int ID { get; set; }
        public int ApplicationId { get; set; }
        public string Locale { get; set; }
        public string Text { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
