//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opc.Ua.Gds.Server.DB
{
    using System.Configuration;
    using Microsoft.EntityFrameworkCore;

    public partial class gdsdbEntities : DbContext
    {
        public gdsdbEntities()
        {
        }

        public gdsdbEntities(DbContextOptions<gdsdbEntities> options)
            : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                string connectionString = ConfigurationManager.ConnectionStrings["gdsdbEntities"]?.ConnectionString;
                optionsBuilder.UseSqlServer(connectionString);
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Application>(entity =>
            {
                entity.ToTable("Applications");
                entity.HasKey(e => e.ID);
                entity.Property(e => e.ID).ValueGeneratedOnAdd();
                entity.HasMany(e => e.ApplicationNames)
                    .WithOne(e => e.Application)
                    .HasForeignKey(e => e.ApplicationId)
                    .OnDelete(DeleteBehavior.Cascade);
                entity.HasMany(e => e.ServerEndpoints)
                    .WithOne(e => e.Application)
                    .HasForeignKey(e => e.ApplicationId)
                    .OnDelete(DeleteBehavior.Cascade);
                entity.HasMany(e => e.CertificateRequests)
                    .WithOne(e => e.Application)
                    .HasForeignKey(e => e.ApplicationId)
                    .OnDelete(DeleteBehavior.Cascade);
                entity.HasMany(e => e.CertificateStores)
                    .WithOne(e => e.Application)
                    .HasForeignKey("Application_ID")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity<ApplicationName>(entity =>
            {
                entity.ToTable("ApplicationNames");
                entity.HasKey(e => e.ID);
                entity.Property(e => e.ID).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<ServerEndpoint>(entity =>
            {
                entity.ToTable("ServerEndpoints");
                entity.HasKey(e => e.ID);
                entity.Property(e => e.ID).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<CertificateRequest>(entity =>
            {
                entity.ToTable("CertificateRequests");
                entity.HasKey(e => e.ID);
                entity.Property(e => e.ID).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<CertificateStore>(entity =>
            {
                entity.ToTable("CertificateStores");
                entity.HasKey(e => e.ID);
                entity.Property(e => e.ID).ValueGeneratedOnAdd();
            });
        }

        public DbSet<ApplicationName> ApplicationNames { get; set; }
        public DbSet<ServerEndpoint> ServerEndpoints { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<CertificateStore> CertificateStores { get; set; }
        public DbSet<CertificateRequest> CertificateRequests { get; set; }
    }
}
