//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opc.Ua.Gds.Server.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gdsdbEntities : DbContext
    {
        public gdsdbEntities()
            : base("name=gdsdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ApplicationName> ApplicationNames { get; set; }
        public DbSet<ServerEndpoint> ServerEndpoints { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<CertificateStore> CertificateStores { get; set; }
        public DbSet<CertificateRequest> CertificateRequests { get; set; }
    }
}
