//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opc.Ua.Gds.Server.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqlRole
    {
        public System.Guid Id { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Name { get; set; }
        public System.Guid UserID { get; set; }
        public int NamespaceIndex { get; set; }
    
        public virtual User User { get; set; }
    }
}
