//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opc.Ua.Gds.Server.DB
{
    using System.Configuration;
    using Microsoft.EntityFrameworkCore;

    public partial class usersdbEntities : DbContext
    {
        public usersdbEntities()
        {
        }

        public usersdbEntities(DbContextOptions<usersdbEntities> options)
            : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                string connectionString = ConfigurationManager.ConnectionStrings["usersdbEntities"]?.ConnectionString;

                if (string.IsNullOrWhiteSpace(connectionString))
                {
                    throw new System.InvalidOperationException(
                        "Missing connection string 'usersdbEntities' in App.config.");
                }

                optionsBuilder.UseSqlServer(connectionString);
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>(entity =>
            {
                entity.ToTable("UserSet");
                entity.HasKey(e => e.ID);
                entity.Property(e => e.ID).ValueGeneratedNever();
                entity.HasMany(e => e.Roles)
                    .WithOne(e => e.User)
                    .HasForeignKey(e => e.UserID)
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity<SqlRole>(entity =>
            {
                entity.ToTable("SqlRoleSet");
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedNever();
            });
        }

        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<SqlRole> SqlRoleSet { get; set; }
    }
}
