<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Quickstarts.DataTypes</RootNamespace>
    <AssemblyName>Quickstarts.DataTypesClient</AssemblyName>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="App.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="DataTypesClient.Config.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Samples\ClientControls.Net4\UA Client Controls.csproj" />
    <ProjectReference Include="..\Common\DataTypes Library.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console">
      <Version>10.0.10</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client">
      <Version>2.0.158.59919-preview</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="WriteValueDlg.Designer.cs" />
    <Compile Remove="WriteValueDlg.cs" />
    <Compile Remove="SubscribeDataDlg.Designer.cs" />
    <Compile Remove="SubscribeDataDlg.cs" />
    <Compile Remove="CallMethodDlg.Designer.cs" />
    <Compile Remove="CallMethodDlg.cs" />
  </ItemGroup>
  <ItemGroup Label="EmbeddedResource items now included by globbing that were not in the original project file">
    <EmbeddedResource Remove="WriteValueDlg.resx" />
    <EmbeddedResource Remove="SubscribeDataDlg.resx" />
    <EmbeddedResource Remove="CallMethodDlg.resx" />
  </ItemGroup>
</Project>