<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Quickstarts.ReferenceServer</RootNamespace>
    <AssemblyName>Quickstarts.ReferenceServer</AssemblyName>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Resources\OPCFoundation.jpg" />
    <EmbeddedResource Include="App.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Quickstarts.ReferenceServer.Config.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ServerControls.Net4\UA Server Controls.csproj" />
    <ProjectReference Include="..\Hosting\Opc.Ua.Samples.Hosting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Bindings.Https">
      <Version>$(OpcUaNetStandardVersion)</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Configuration">
      <Version>$(OpcUaNetStandardVersion)</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Quickstarts.Servers">
      <Version>$(OpcUaNetStandardVersion)</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="Aggregates\TimeSlice.cs" />
    <Compile Remove="Aggregates\InterpolativeAggregate.cs" />
    <Compile Remove="Aggregates\Experiment.cs" />
    <Compile Remove="Aggregates\BoundingValue.cs" />
    <Compile Remove="Aggregates\Aggregators.cs" />
    <Compile Remove="Aggregates\AggregateManager.cs" />
    <Compile Remove="Aggregates\AggregateCursor.cs" />
    <Compile Remove="Aggregates\AggregateCalculator.cs" />
  </ItemGroup>
  <PropertyGroup />
</Project>