#
# Build all .Net Core projects on all platforms
#
parameters:
  buildoption: ''
  agents: '@{}'
jobs:
- job: buildprep
  displayName: Prepare Build Jobs
  pool:
    vmImage: 'windows-2019'
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  steps:
  - task: PowerShell@2
    name: buildmatrix
    displayName: Prepare Solutions
    inputs:
      targetType: filePath
      filePath: ./.azurepipelines/get-matrix.ps1
      arguments: -FileName azure-pipelines.yml -AgentTable ${{ parameters.agents }}
- job: buildall
  displayName: Build
  dependsOn: buildprep
  strategy:
    matrix: $[dependencies.buildprep.outputs['buildmatrix.jobMatrix'] ]
  pool:
    vmImage: $(poolImage)
  steps:
  - task: NuGetAuthenticate@1
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '>=5.8.x'
  - task: DotNetCoreCLI@2
    displayName: Release Restore
    inputs:
      command: restore
      projects: '**/NetCore*.csproj'
      arguments: '--configuration Release ${{ parameters.buildoption }}'
      includeNuGetOrg: true
      feedsToUse: config
      nugetConfigPath: $(Build.SourcesDirectory)/Nuget.Config
  - task: DotNetCoreCLI@2
    displayName: Release Build
    inputs:
      command: build
      projects: '**/NetCore*.csproj'
      arguments: '--no-restore --configuration Release ${{ parameters.buildoption }}'
  - task: DotNetCoreCLI@2
    displayName: Debug Restore
    inputs:
      command: restore
      projects: '**/NetCore*.csproj'
      arguments: '--configuration Debug ${{ parameters.buildoption }}'
      includeNuGetOrg: true
      feedsToUse: config
      nugetConfigPath: $(Build.SourcesDirectory)/Nuget.Config
  - task: DotNetCoreCLI@2
    displayName: Debug Build
    inputs:
      command: build
      projects: '**/NetCore*.csproj'
      arguments: '--no-restore --configuration Debug ${{ parameters.buildoption }}'
