<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Opc.Ua.Client.Controls</RootNamespace>
    <AssemblyName>Opc.Ua.ClientControls</AssemblyName>
    <AssemblyOriginatorKeyFile></AssemblyOriginatorKeyFile>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Browse\AttributeListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Browse\BrowseListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Browse\BrowseTreeCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Browse\NodeListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="ClientUtils.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\ClientUtils.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\AttrributesListViewCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\BrowseNodeCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\BrowseTreeViewCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\CallRequestListViewCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\ConnectServerCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\EditComplexValueCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\EditValueCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\EventFilterListViewCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\EventListViewCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\HistoryDataListView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\HistoryEventCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\ReadRequestListViewCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\SelectNodeCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\SubscribeDataListViewCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\TypeFieldsListViewCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\Client\WriteRequestListViewCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\DiscoveredServerOnNetworkListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\SelectHostCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\DiscoveredServerListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\HostListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Configuration\Common %28OLD%29\GuiUtils.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\EditDataValueCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\EditValueCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\EventListView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\ReferenceListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Configuration\Common %28OLD%29\BaseListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Configuration\Common %28OLD%29\BaseTreeCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Configuration\Common %28OLD%29\DataListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Configuration\Common %28OLD%29\NodeIdCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Configuration\Common %28OLD%29\ReferenceTypeCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Configuration\CertificateListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Configuration\CertificatePropertiesListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Configuration\CertificateStoreCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Configuration\CertificateStoreTreeCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Configuration\SelectUrlsCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Configuration\SelectProfileCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Configuration\SelectCertificateStoreCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Configuration\SelectFileCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Endpoints\ConfiguredServerListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Endpoints\EndpointSelectorCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="HeaderBranding.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Images\" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console">
      <Version>10.0.8</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Core">
      <Version>1.5.378.156</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client">
      <Version>1.5.378.156</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client.ComplexTypes">
      <Version>1.5.378.156</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Configuration">
      <Version>1.5.378.156</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="Endpoints\SelectHostCtrl.Designer.cs" />
    <Compile Remove="Endpoints\SelectHostCtrl.cs" />
    <Compile Remove="Endpoints\HostListDlg.Designer.cs" />
    <Compile Remove="Endpoints\HostListDlg.cs" />
    <Compile Remove="Endpoints\HostListCtrl.Designer.cs" />
    <Compile Remove="Endpoints\HostListCtrl.cs" />
    <Compile Remove="Endpoints\DiscoveredServerListDlg.Designer.cs" />
    <Compile Remove="Endpoints\DiscoveredServerListDlg.cs" />
    <Compile Remove="Endpoints\DiscoveredServerListCtrl.Designer.cs" />
    <Compile Remove="Endpoints\DiscoveredServerListCtrl.cs" />
    <Compile Remove="Configuration\UserNamePasswordDlg.Designer.cs" />
    <Compile Remove="Configuration\UserNamePasswordDlg.cs" />
    <Compile Remove="Configuration\Common (OLD)\ExceptionDlg.Designer.cs" />
    <Compile Remove="Configuration\Common (OLD)\ExceptionDlg.cs" />
    <Compile Remove="Common\ViewEventDetailsDlg.Designer.cs" />
    <Compile Remove="Common\ViewEventDetailsDlg.cs" />
    <Compile Remove="Common\SelectNodeDlg.Designer.cs" />
    <Compile Remove="Common\SelectNodeDlg.cs" />
    <Compile Remove="Common\SelectNodeCtrl.Designer.cs" />
    <Compile Remove="Common\SelectNodeCtrl.cs" />
    <Compile Remove="Common\SelectLocaleDlg.Designer.cs" />
    <Compile Remove="Common\SelectLocaleDlg.cs" />
    <Compile Remove="Common\HistoryDataListView.Designer.cs" />
    <Compile Remove="Common\HistoryDataListView.cs" />
    <Compile Remove="Common\EditComplexValueDlg.Designer.cs" />
    <Compile Remove="Common\EditComplexValueDlg.cs" />
    <Compile Remove="Common\EditAnnotationDlg.Designer.cs" />
    <Compile Remove="Common\EditAnnotationDlg.cs" />
    <Compile Remove="Common\ConnectServerCtrl.Designer.cs" />
    <Compile Remove="Common\ConnectServerCtrl.cs" />
    <Compile Remove="Common\BrowseNodeCtrl.Designer.cs" />
    <Compile Remove="Common\BrowseNodeCtrl.cs" />
  </ItemGroup>
  <ItemGroup Label="EmbeddedResource items now included by globbing that were not in the original project file">
    <EmbeddedResource Remove="Endpoints\SelectHostCtrl.resx" />
    <EmbeddedResource Remove="Endpoints\HostListDlg.resx" />
    <EmbeddedResource Remove="Endpoints\HostListCtrl.resx" />
    <EmbeddedResource Remove="Endpoints\DiscoveredServerListDlg.resx" />
    <EmbeddedResource Remove="Endpoints\DiscoveredServerListCtrl.resx" />
    <EmbeddedResource Remove="Configuration\UserNamePasswordDlg.resx" />
    <EmbeddedResource Remove="Configuration\Common (OLD)\ExceptionDlg.resx" />
    <EmbeddedResource Remove="Common\ViewEventDetailsDlg.resx" />
    <EmbeddedResource Remove="Common\SelectNodeDlg.resx" />
    <EmbeddedResource Remove="Common\SelectNodeCtrl.resx" />
    <EmbeddedResource Remove="Common\SelectLocaleDlg.resx" />
    <EmbeddedResource Remove="Common\HistoryDataListView.resx" />
    <EmbeddedResource Remove="Common\EditComplexValueDlg.resx" />
    <EmbeddedResource Remove="Common\EditAnnotationDlg.resx" />
    <EmbeddedResource Remove="Common\ConnectServerCtrl.resx" />
    <EmbeddedResource Remove="Common\BrowseNodeCtrl.resx" />
  </ItemGroup>
  <PropertyGroup />
</Project>
