<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Opc.Ua.Sample</RootNamespace>
    <AssemblyName>Opc.Ua.SampleControls</AssemblyName>
    <AssemblyOriginatorKeyFile></AssemblyOriginatorKeyFile>
    <PublishUrl>http://localhost/Opc.Ua.SampleControls/</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Web</InstallFrom>
    <UpdateEnabled>true</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <IsWebBootstrapper>true</IsWebBootstrapper>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Common\ArgumentListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Sessions\BrowseListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Sessions\TypeHierarchyListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Sessions\TypeNavigatorCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Subscriptions\HistoryReadDetails.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Subscriptions\DataChangeNotificationListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Subscriptions\FilterOperandListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Subscriptions\SelectClauseListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\PerformanceResultsListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Subscriptions\WriteValueListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\DataValueListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Subscriptions\ReadValueListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\NodeListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\PropertyListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Subscriptions\ContentFilterElementListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Subscriptions\EventNotificationListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Subscriptions\MonitoredItemConfigCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Subscriptions\NotificationMessageListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Subscriptions\MonitoredItemStatusCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Sessions\SessionTreeCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Common\AttributeListCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Sessions\BrowseTreeCtrl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClientControls.Net4\UA Client Controls.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Images\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console">
      <Version>10.0.10</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client.ComplexTypes">
      <Version>2.0.158.59919-preview</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Server">
      <Version>2.0.158.59919-preview</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Label="EmbeddedResource items now included by globbing that were not in the original project file">
    <EmbeddedResource Remove="Subscriptions\HistoryReadDetailsCtrl.resx" />
  </ItemGroup>
  <PropertyGroup />
</Project>
