<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Quickstarts.HistoricalAccessServer</RootNamespace>
    <AssemblyName>Quickstarts.HistoricalAccessServer</AssemblyName>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\..\..\bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\..\..\bin\Release\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Data\Dynamic\Int32.txt" />
    <EmbeddedResource Include="Data\Dynamic\Double.txt" />
    <EmbeddedResource Include="Data\Dynamic\Boolean.txt" />
    <EmbeddedResource Include="Data\Dynamic\Byte.txt" />
    <EmbeddedResource Include="Data\Dynamic\DateTime.txt" />
    <EmbeddedResource Include="Data\Dynamic\Float.txt" />
    <EmbeddedResource Include="Data\Dynamic\Int16.txt" />
    <EmbeddedResource Include="Data\Dynamic\Int64.txt" />
    <EmbeddedResource Include="Data\Dynamic\SByte.txt" />
    <EmbeddedResource Include="Data\Dynamic\String.txt" />
    <EmbeddedResource Include="Data\Dynamic\UInt16.txt" />
    <EmbeddedResource Include="Data\Dynamic\UInt32.txt" />
    <EmbeddedResource Include="Data\Dynamic\UInt64.txt" />
    <EmbeddedResource Include="Data\Sample\Boolean.txt" />
    <EmbeddedResource Include="Data\Sample\Byte.txt" />
    <EmbeddedResource Include="Data\Sample\ByteString.txt" />
    <EmbeddedResource Include="Data\Sample\DateTime.txt" />
    <EmbeddedResource Include="Data\Sample\Double.txt" />
    <EmbeddedResource Include="Data\Sample\Float.txt" />
    <EmbeddedResource Include="Data\Sample\Int16.txt" />
    <EmbeddedResource Include="Data\Sample\Int32.txt" />
    <EmbeddedResource Include="Data\Sample\Int64.txt" />
    <EmbeddedResource Include="Data\Sample\SByte.txt" />
    <EmbeddedResource Include="Data\Sample\String.txt" />
    <EmbeddedResource Include="Data\Sample\UInt16.txt" />
    <EmbeddedResource Include="Data\Sample\UInt32.txt" />
    <EmbeddedResource Include="Data\Sample\UInt64.txt" />
    <Content Include="HistoricalAccessServer.Config.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </Content>
    <EmbeddedResource Include="App.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Data.txt" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Samples\ServerControls.Net4\UA Server Controls.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console">
      <Version>10.0.10</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Server">
      <Version>2.0.0-preview.2</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="UnderlyingSystem\UnderlyingSystemTagType.cs" />
    <Compile Remove="UnderlyingSystem\UnderlyingSystemTag.cs" />
    <Compile Remove="UnderlyingSystem\UnderlyingSystemSegment.cs" />
    <Compile Remove="UnderlyingSystem\UnderlyingSystemDataType.cs" />
    <Compile Remove="UnderlyingSystem\UnderlyingSystemBlock.cs" />
    <Compile Remove="Model\SegmentState.cs" />
    <Compile Remove="Model\SegmentBrowser.cs" />
    <Compile Remove="Model\Namespaces.cs" />
    <Compile Remove="Model\ModelUtils.cs" />
    <Compile Remove="Model\BlockState.cs" />
  </ItemGroup>
</Project>