<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Quickstarts.ReferenceClient</RootNamespace>
    <AssemblyName>Quickstarts.ReferenceClient</AssemblyName>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="App.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Quickstarts.ReferenceClient.Config.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClientControls.Net4\UA Client Controls.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console">
      <Version>10.0.10</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Bindings.Https">
      <Version>2.0.0-preview.2</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client">
      <Version>2.0.0-preview.2</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Configuration">
      <Version>2.0.0-preview.2</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Core">
      <Version>2.0.0-preview.2</Version>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup />
</Project>